version: '3.8'
services:
  db:
    container_name: potterdb-db
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always

  web:
    build: .
    container_name: potterdb-web
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password

    command: ["sh", "-c", "rails server -b 0.0.0.0"]
